name: ci-ristretto-tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  ristretto-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run Unit Tests
        run: |
          go env -w GOTOOLCHAIN=go1.25.0+auto
          go test -timeout=20m -race -covermode atomic -coverprofile=covprofile ./...
      - name: Save coverage profile
        uses: actions/upload-artifact@v4
        with:
          name: covprofile
          path: ./covprofile
